front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

# front_product:
#     path: /product
#     defaults: { _controller: FrontBundle:Product:index }

front_product_detail:
    path: /product-detail/{slug}
    defaults: { _controller: FrontBundle:Product:detail }
    methods: GET
front_upload:
    path: /product-upload
    defaults: { _controller: FrontBundle:Default:index }