front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_category:
    path: /category/{slug}/{page}
    defaults: { _controller: FrontBundle:Product:category, slug: null, page: 1}
    methods: GET

front_product_detail:
    path: /product/{category}/{slug}
    defaults: { _controller: FrontBundle:Product:detail, category: null, slug: null }
    methods: GET

front_contact_us:
    path: /contact-us
    defaults: { _controller: FrontBundle:Default:contactUs }

front_cart:
    path: /cart
    defaults: { _controller: FrontBundle:Cart:index }

front_cart_update:
    path: /cart/update
    defaults: { _controller: FrontBundle:Cart:update }

front_cart_checkout:
    path: /cart/checkout
    defaults: { _controller: FrontBundle:Cart:checkout }

front_cart_remove_item:
    path: /cart/remove-item
    defaults: { _controller: FrontBundle:Cart:removeItem }

front_cart_success:
    path: /cart/success
    defaults: { _controller: FrontBundle:Cart:success }
