front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_category:
    path: /category/{slug}
    defaults: { _controller: FrontBundle:Product:category, slug: null}
    methods: GET

front_product_detail:
    path: /product/{category}/{slug}
    defaults: { _controller: FrontBundle:Product:detail, category: null, slug: null }
    methods: GET

front_contact_us:
    path: /contact-us
    defaults: { _controller: FrontBundle:Default:contactUs }