services:
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    utils.product.manager:
        class: FrontBundle\Utils\ProductManager
        arguments: ['@doctrine.orm.entity_manager','@service_container']
