services:
    utils.global.manager:
        class: FrontBundle\Utils\GlobalManager
        arguments: ['@doctrine.orm.entity_manager','@service_container']
    utils.product.manager:
        class: FrontBundle\Utils\ProductManager
        arguments: ['@doctrine.orm.entity_manager','@service_container']
    utils.banner.manager:
        class: FrontBundle\Utils\BannerManager
        arguments: ['@doctrine.orm.entity_manager','@service_container']
    utils.cart.manager:
        class: FrontBundle\Utils\CartManager
        arguments: ['@service_container']
    app.form.type.cart:
        class: AppBundle\Form\CartType
        tags:
            - { name: form.type }
    utils.email.manager:
        class: FrontBundle\Utils\EmailManager
        arguments: ['@doctrine.orm.entity_manager','@service_container', '@templating']
