services:
    namer.product_image_file:
        class: AppBundle\Helpers\ProductImageNamer
        tags:
            - { name: namer }
    namer.website_logo_file:
        class: AppBundle\Helpers\WebsiteLogoNamer
        tags:
            - { name: namer }
