services:
    namer.product_image_file:
        class: AppBundle\Helpers\ProductImageNamer
        tags:
            - { name: namer }
    namer.website_logo_file:
        class: AppBundle\Helpers\WebsiteLogoNamer
        tags:
            - { name: namer }
    namer.banner_image_file:
        class: AppBundle\Helpers\BannerImageNamer
        tags:
            - { name: namer }
    utils.admin.global.manager:
        class: AdminBundle\Utils\GlobalManager
        arguments: ['@doctrine.orm.entity_manager','@service_container']        
