<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    public function getAllBanners()
    {
        $query   = $this->createQueryBuilder('bn')
                    ->select("bn.id, bn.title, bn.link, bn.image, bn.type")
                    ->getQuery();

        $results = $query->getResult();
        return $results;
    }
}
