<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findAllCategories($params)
    {
        $query    = $this->createQueryBuilder('cat')
                    ->select("cat.id, cat.name, cat.slug")
                    ->setMaxResults($params['limit'])
                    ->getQuery();

        $results = $query->getResult();
        return $results;
    }

    public function getCategory($slug)
    {
        $query   = $this->createQueryBuilder('cat')
                    ->select('cat.id, cat.name, cat.slug, cat.description')
                    ->where('cat.slug = :slug')
                    ->setParameter('slug', $slug)
                    ->getQuery();

        $results = $query->getOneOrNullResult();
        return $results;
    }
}
