<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getOrderStatistics($year = null)
    {
        $year  = $year ? $year : date('Y');
        $query = $this->createQueryBuilder('o')
                      ->select("COUNT(o.id) as number, MONTH(o.createdAt) as month")
                      ->where('YEAR(o.createdAt) = :currentYear')
                      ->setParameter('currentYear', $year)
                      ->groupBy('month')
                      ->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
