imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@FrontBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.product_images: /uploads/images/products

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.root_dir%/../vendor/javiereguiluz/easyadmin-bundle/Resources/views': easyadmin_template

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Configure the FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        admin@hashop-local.vn
        sender_name:    Admin

# Configure Easy admin
easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            edit:
                fields: ['id', 'email']
        Category:
            class: AppBundle\Entity\Category
            form:
                fields: ['name', 'parentId', 'description']
            # templates:
            #     field_array: ':easy_admin:field_array.html.twig'
        Product:
            class: AppBundle\Entity\Product
            form:
                fields: ['name', { property: 'description', type: 'textarea' }, 'price', { property: 'imageFile', type: 'vich_image' }]
            # edit:
            #     fields: ['name', 'description', 'price', { property: 'imageFile', type: 'vich_image' }]

    design:
        brand_color: '#1ABC9C'
        menu:
            - { entity: 'User', icon: 'user' }
            - { entity: 'Category', icon: 'file-text-o' }
            - { entity: 'Product', icon: 'list' }

# Vich configuration
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/products'

tweede_golf_media:
    max_per_page: 24  # this is optional (default is 18)
    file_entity: 'AppBundle:File'  # this is required

liip_imagine:
    filter_sets:
        tgmedia_thumbnail:
            quality: 80
            filters:
                thumbnail: { size: [200, 150], mode: outbound }

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    theme:
        advanced:
            plugins:
                - "media emoticons link image textcolor code table template fileupload"
            toolbar1: "insertfile undo redo | styleselect | bold italic | underline strikethrough subscript superscript | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | emoticons | forecolor backcolor table fileupload"
            image_advtab: true
